
<div class="span3">
	<!-- widget  -->
	<div class="widget">
		<div class="widget-header">
			<i class="icon-star"></i>
			<h3><?php echo lang("design:text_options") ?></h3>
		</div>
		<!-- /widget-header -->
		<div class="widget-content">
			<!-- options -->
			<label for="designtext"><i class=" icon-edit"></i><?php echo lang("design:enter_text") ?></label>
			<!-- Texts on T-shirt -->
			<div id="texts" class="clearfix">
				<!-- Text where tro put text -->
				<textarea type="text" id="designtext" name="designtext"
					placeholder="Text" class="span12"></textarea>
				<!-- button to generate new textarea -->
				<button class="btn pull-right nexText">
					<i class="icon-plus"></i> <?php echo lang("design:new_text")?>
						</button>
			</div>
			<!-- /.text -->

			<hr>

			<h5>
				<i class="icon-zoom-in"></i><?php echo lang("design:font_size")?>
					</h5>
			<!-- Slider to change font size -->
			<div class="slider">
				<!-- default value -->
				<div class="size">12px</div>
				<!-- slider generated by jQuery UI -->
				<div id="slider"></div>
			</div>

			<hr>
			<!-- separator -->
			<!-- Font color to change color - <i class="icon-magic"></i> icons using Fontawesome  -->
			<h5>
				<i class="icon-magic"></i> <?php echo lang("design:font_color")?>
					</h5>
			<!-- input colors -->
			<input id="color" type="text" class="pick-a-color span8">

			<hr>
			<!-- section to change Fonts -->
			<h5>
				<i class="icon-beaker"></i> <?php echo lang("design:font")?>
					</h5>
			<!-- btn groupe using bootstrap - dropup : to show menu up -->
			<div class="btn-group dropup">
				<button class="btn  span12"><?php echo lang("design:select_font") ?></button>
				<!--  -->
				<button class="btn dropdown-toggle" data-toggle="dropdown">
					<span class="caret"></span>
				</button>
				<ul class="dropdown-menu " id="font">
					<li><a href="javascript:" data-font="Bigelow+Rules"
						data-toggle="tooltip" data-placement="right" title="Bigelow+Rules"><img
							src="<?php echo Asset::get_filepath_img('module::Bigelow_Rules1.png');?>"
							alt="Bigelow+Rules"></a></li>
					<li><a href="javascript:" data-font="Mrs+Sheppards"
						data-toggle="tooltip" data-placement="right" title="Mrs+Sheppards"><img
							src="<?php Asset::get_filepath_img('module::Mrs+Sheppards.png');?>"
							alt="Mrs+Sheppards"></a></li>
					<li><a href="javascript:" data-font="Joti+One"
						data-toggle="tooltip" data-placement="right" title="Joti+One"><img
							src="<?php Asset::get_filepath_img('module::Joti+One.png');?>"
							alt="Joti+One"></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>