<section class="item">
	<br/>
<div class="container-fluid">
	<div class="yes"></div>
	<div class="row-fluid content item">
		<div class="span3">
			<!-- widget  -->
			<div class="widget">

				<div class="widget-header">

					<i class="icon-star"></i>
					<h3>Text Options</h3>

				</div>
				<!-- /widget-header -->

				<div class="widget-content">
					<!-- options -->
					<label for="designtext"><i class=" icon-edit"></i> Enter text below</label>
					<!-- Texts on T-shirt -->
					<div id="texts" class="clearfix">
						<!-- Text where tro put text -->
						<textarea type="text" id="designtext" name="designtext"
							placeholder="Text" class="span12">lorem lepsum</textarea>
						<!-- button to generate new textarea -->
						<button class="btn pull-right nexText">
							<i class="icon-plus"></i> New text
						</button>
					</div>
					<!-- /.text -->

					<hr>

					<h5>
						<i class="icon-zoom-in"></i> Font Size
					</h5>
					<!-- Slider to change font size -->
					<div class="slider">
						<!-- default value -->
						<div class="size">12px</div>
						<!-- slider generated by jQuery UI -->
						<div id="slider"></div>
					</div>

					<hr>
					<!-- separator -->
					<!-- Font color to change color - <i class="icon-magic"></i> icons using Fontawesome  -->
					<h5>
						<i class="icon-magic"></i> Font Color
					</h5>
					<!-- input colors -->
					<input id="color" type="text" class="pick-a-color span8">

					<hr>
					<!-- section to change Fonts -->
					<h5>
						<i class="icon-beaker"></i> Fonts
					</h5>
					<!-- btn groupe using bootstrap - dropup : to show menu up -->
					<div class="btn-group dropup">

						<button class="btn  span12">Select Font</button>
						<!--  -->
						<button class="btn dropdown-toggle" data-toggle="dropdown">

							<span class="caret"></span>

						</button>




						<ul class="dropdown-menu tooltip-show" id="font">
							<li><a href="javascript:" data-font="Bigelow+Rules"
								data-toggle="tooltip" data-placement="right"
								title="Bigelow+Rules"><img
									src="<?php echo Asset::img(array('module::Bigelow_Rules1.png'), 'Some thumbnails');?>"
									alt="Bigelow+Rules"></a></li>
							<li><a href="javascript:" data-font="Mrs+Sheppards"
								data-toggle="tooltip" data-placement="right"
								title="Mrs+Sheppards"><img
									src="<?php Asset::img(array('module::Mrs+Sheppards.png'), 'Some thumbnails');?>"
									alt="Mrs+Sheppards"></a></li>
							<li><a href="javascript:" data-font="Joti+One"
								data-toggle="tooltip" data-placement="right" title="Joti+One"><img
									src="<?php Asset::img(array('module::Joti+One.png'), 'Some thumbnails');?>"
									alt="Joti+One"></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="span6">
			<div class="designContainer" id="printable">
				<div id="imagesContainer"></div>
				<div class="text t designtext1 no-delete">
					<i class="icon-remove action text-error" data-action="remove"></i>
					<p>lorem lepsum</p>
					<i class="icon-edit action" data-action="fsontSize"></i>
				</div>
				<img id="Tshirtsrc"
					src="<?php Asset::img(array('module::Joti+One.png'), 'Some thumbnails');?>"
					alt="White T-shirt">
			</div>
			<hr>
			<div class="navbar">
				<div class="navbar-inner">
					<ul class="nav unstyled">
						<li><a href="#myModal" role="button" data-toggle="modal"><i
								class="icon-eye-open"></i> Preview</a></li>
						<li class="divider-vertical"></li>
						<li><a href="javascript:" onclick="PrintElem("
							#printable")" class="print"><i class="icon-print"></i> Print</a>
						</li>
						<li class="divider-vertical"></li>
						<li><a class="dropdown-toggle export" data-toggle="dropdown"
							href="javascript:"> Export </a></li>

						<li class="divider-vertical"></li>

						<li>
							<div class="fb-share-button" data-type="icon_link"
								style="line-height: 28px; padding: 0 0 0 20px;"></div>

						</li>

					</ul>
				</div>
			</div>
		</div>

		<div class="span3">
			<div class="widget">
				<div class="widget-header">
					<i class="icon-star"></i>
					<h3>Images Options</h3>
				</div>
				<div class="widget-content">
					<h5>
						<i class="icon-picture"></i> Add image
					</h5>
					<input type="file" id="imgInp" class="span8" name="file" />
					<hr>
					<h5>
						<i class="icon-tags"></i> Collections
					</h5>
					<ul class="tshirts unstyled clearfix tooltip-show">
						<li><a href="#" data-toggle="tooltip" data-placement="bottom"
							title='White T-shirt'> <img
								src="<?php Asset::img(array('module::02.jpg'), 'Some thumbnails');?>"
								alt="White T-shirt">
						</a></li>
						<li><a href="#" data-toggle="tooltip" data-placement="bottom"
							title='Tshirt 2'> <img
								src="<?php Asset::img(array('module::13.jpg'), 'Some thumbnails');?>"
								alt="Tshirt 2">
						</a></li>
						<li><a href="#" data-toggle="tooltip" data-placement="bottom"
							title='tshirt 1'> <img
								src="<?php Asset::img(array('module::2.jpg'), 'Some thumbnails');?>"
								alt="tshirt 1">
						</a></li>
					</ul>
					<hr>
					<h5>
						<i class="icon-cog"></i> Help
					</h5>
					<p class="help">
						<span class="badge badge-info"><i class="icon-edit"></i></span> :
						Click To edit Text or Click on the Text(font size, Font, color) <br>
						<span class="badge badge-info"><i class="icon-remove"></i></span>
						: Click To remove text after confirmation <br> <span
							class="badge badge-info"><span
							class="ui-icon ui-icon-white ui-icon-gripsmall-diagonal-se"></span></span>
						: Drag To resize images
					</p>
				</div>
			</div>
		</div>


	</div>
</div>
<script>
 jQuery(document).ready(function ($) { 
         $('.export').click(function(){
            //hide options
            $('#printable').find('i').css('display', 'none');
            $('#printable').find('.ui-icon').css('display', 'none');
            //get printable section
             var exportCanvas = document.getElementById('printable');
             //get convas container
             var canvasContainer = document.getElementById('convascontent');
                //export canvas to convascontainer
                html2canvas(exportCanvas, {
                    //when finished fucntion
                onrendered: function(canvas) {
                    // initialize canvas container (if we generate another canvas)
                    $('#convascontent').html(' ');
                    // append canvas to container
                    canvasContainer.appendChild(canvas);
                    //add id attribute to the canvas
                    $('#convascontent').find('canvas').attr('id','mycanvas');
                    // display options again
                    $('#printable').find('i').css('display', 'block');
                    $('#printable').find('.ui-icon').css('display', 'block');
                    //document.getElementsByTagName("UL")
                }
            });
                $('body').append("<div class='overlay'>Generating your design</div>");

                setTimeout(function(){
                    var oCanvas = document.getElementById("mycanvas"); 
                    //var testCanvas = document.getElementById("testCanvas");  
                    var canvasData = oCanvas.toDataURL("image/png");

                    var postData = "canvasData="+canvasData;

                    //var debugConsole= document.getElementById("debugConsole");  
                    //debugConsole.value=canvasData;

                    //alert("canvasData ="+canvasData );      
                    var ajax = new XMLHttpRequest();
                    ajax.open("POST","save.php.htm"/*tpa=http://99bootstrap.com/TshirtDesigner/wordpress/wp-content/plugins/tshirtdesigner/save.php*/,true);    
                    ajax.setRequestHeader('Content-Type', 'canvas/upload');
                    //ajax.setRequestHeader('Content-TypeLength', postData.length);

                    ajax.onreadystatechange=function()
                    {
                        if (ajax.readyState == 4)
                        { 
                            $('.overlay').remove();
                            //alert(ajax.responseText);
                            // Write out the filename.
                            $('.yes').html("<div class='alert alert-success'>If you can't download you file here is a link , Saved as <br><a  target='_blank' class='download' download href='http://99bootstrap.com/TshirtDesigner/wordpress/wp-content/plugins/tshirtdesigner/designs/" + ajax.responseText + "' donwload='http://99bootstrap.com/TshirtDesigner/wordpress/wp-content/plugins/tshirtdesigner/designs/" + ajax.responseText + "'>"+ajax.responseText+"</a></div>");
                            res =  ajax.responseText;

                        }
                    }
                    ajax.send(postData);
                    
                }, 2000);
        //return false;
       });


    });



    </script>
</section>